# SPDX-License-Identifier: GPL-2.0-or-later

unit_test_sources = files(
'collection-file-source.cc',
'filecache.cc',
'filedata/filedata.cc',
'filedata/filelist.cc',
'filedata/ref.cc',
'history-list.cc',
'keyboard-shortcuts.cc',
'layout-image-navigation.cc',
'pixbuf-util.cc',
'ui-tree-edit.cc')

project_sources += unit_test_sources
