name: geeqie
title: Geeqie
base: core24
adopt-info: geeqie

summary: Lightweight, fast GTK image viewer

source-code: http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=summary
issues: https://github.com/BestImageViewer/geeqie/issues
website: https://www.geeqie.org/
contact: geeqie@freelists.org

grade: devel
confinement: strict

package-repositories:
  - type: apt
    url: http://archive.ubuntu.com/ubuntu/
    suites: [ noble ]              # core24 = Ubuntu 24.04 (noble)
    components: [ main, universe ] # jpgicc is in universe
    key-id: 790BC7277767219C42C86F933B4FE6ACC0B21F32

apps:
  geeqie:
    command-chain:
      - bin/env-lapack.sh
    command: usr/bin/geeqie
    extensions: [ gnome ]
    environment:
      LD_LIBRARY_PATH: "\$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$LD_LIBRARY_PATH"
      MAGICK_CONFIGURE_PATH: "$SNAP/etc/ImageMagick-6: $SNAP/usr/share/ImageMagick-6: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6/config-Q16: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6.9.12/config-Q16"
      MAGICK_CODER_MODULE_PATH:  "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6/modules-Q16/coders: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6.9.12/modules-Q16/coders"
      MAGICK_HOME: "$SNAP/usr"
      PATH: "$SNAP/usr/bin:$SNAP/bin:$PATH"
    plugs:
      - home
      - removable-media
      - network
      - gsettings
      - opengl
      - wayland
      - x11

slots:
  geeqie-dbus:
    interface: dbus
    bus: session
    name: org.geeqie.Geeqie

parts:
  geeqie:
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr
      - --wrap-mode=default
      - -Dgps-map=disabled
      - -Dextended_stacktrace=disabled
      - -Dunit_tests=disabled
    parse-info:
      - usr/share/metainfo/org.geeqie.Geeqie.appdata.xml
    stage-packages:
      - bc
      - exiftool
      - exiftran
      - exiv2
      - gphoto2
      - imagemagick
      - imagemagick-6-common
      - imagemagick-6.q16
      - libblas3
      - libchamplain-0.12-0
      - libchamplain-gtk-0.12-0
      - libclutter-1.0-0
      - libclutter-gtk-1.0-0
      - libdjvulibre21
      - libexif12
      - libexiv2-27
      - libffmpegthumbnailer4v5
      - libfftw3-double3
      - libgexiv2-2
      - libgfortran5
      - libgspell-1-2
      - libheif1
      - libimath-3-1-29
      - libjpeg-turbo8
      - liblapack3
      - liblcms2-2
      - liblua5.3-0
      - libopenexr-3-1-30
      - libpng16-16
      - libpoppler-glib8
      - libproxy1-plugin-gsettings
      - libproxy1v5
      - libraw23
      - libtiff6
      - libwebp7
      - libzstd1
      - shared-mime-info
      - yad
      - zenity
    override-prime: |
      set -eux
      craftctl default
      ver="$(git describe --tags --dirty --always 2>/dev/null \
            || date +'%Y%m%d').edge"
      craftctl set version="$ver"
      # Create compat symlinks because dpkg alternatives aren't run in snaps
      for tool in convert mogrify identify composite compare; do
        if [ -x "$CRAFT_PRIME/usr/bin/${tool}-im6.q16" ] && [ ! -e "$CRAFT_PRIME/usr/bin/$tool" ]; then
          ln -s "${tool}-im6.q16" "$CRAFT_PRIME/usr/bin/$tool"
        fi
      done
      sed -i 's|/usr/lib/|${SNAP}/usr/lib/|g' "$CRAFT_PRIME/etc/ImageMagick-6/delegates.xml" || true
  launcher:
    plugin: nil
    source: .
    override-build: |
      install -Dm755 snap/local/env-lapack.sh "$CRAFT_PART_INSTALL/bin/env-lapack.sh"
    stage:
      - bin/env-lapack.sh
    build-environment:
      - LDFLAGS: -Wl,--as-needed -lzstd
      - MESON_PACKAGE_CACHE_DIR: $CRAFT_PART_BUILD/meson-packagecache
    build-packages:
      - appstream
      - build-essential
      - curl
      - gettext
      - libarchive-dev
      - libcfitsio-dev
      - libchamplain-0.12-dev
      - libdjvulibre-dev
      - libdw-dev
      - libffmpegthumbnailer-dev
      - libfftw3-dev
      - libgexiv2-dev
      - libglib2.0-dev
      - libgspell-1-dev
      - libgtk-3-dev
      - libheif-dev
      - libimath-dev
      - libjpeg-turbo8-dev
      - libjxl-dev
      - liblcms2-dev
      - liblua5.3-dev
      - libomp-dev
      - libopenexr-dev
      - libpango1.0-dev
      - libpng-dev
      - libpoppler-glib-dev
      - libraw-dev
      - librsvg2-dev
      - libtiff-dev
      - libunwind-dev
      - libwebp-dev
      - libzstd-dev
      - meson
      - ninja-build
      - pandoc
      - pkg-config
      - xsltproc
      - yelp-tools
