name: geeqie
title: Geeqie
base: core24
adopt-info: geeqie

summary: Lightweight, fast GTK image viewer
description: |
  Geeqie is a fast GTK image viewer for browsing large image collections.

grade: devel
confinement: strict

# Needed to access 'universe' packages on noble (core24)
package-repositories:
  - type: apt
    url: http://archive.ubuntu.com/ubuntu/
    suites: [ noble ]
    components: [ main, universe ]
    key-id: 790BC7277767219C42C86F933B4FE6ACC0B21F32

apps:
  geeqie:
    command-chain:
      - bin/env-imagemagick.sh
      - bin/env-lapack.sh
    command: usr/bin/geeqie
    extensions: [ gnome ]
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$LD_LIBRARY_PATH"
      MAGICK_CONFIGURE_PATH: "$SNAP/etc/ImageMagick-6:$SNAP/usr/share/ImageMagick-6:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6/config-Q16:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6.9.12/config-Q16"
      MAGICK_CODER_MODULE_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6/modules-Q16/coders:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ImageMagick-6.9.12/modules-Q16/coders"
      MAGICK_HOME: "$SNAP/usr"
      PATH: "$SNAP/usr/bin:$SNAP/bin:$PATH"
    plugs:
      - home
      - removable-media
      - gsettings
      - wayland
      - x11
      - opengl
      - network

slots:
  geeqie-dbus:
    interface: dbus
    bus: session
    name: org.geeqie.Geeqie

parts:
  geeqie:
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr
      - --wrap-mode=default
      - -Dgps-map=disabled
      - -Dextended_stacktrace=disabled
      - -Dunit_tests=disabled
    parse-info:
      - usr/share/metainfo/org.geeqie.Geeqie.appdata.xml

    # --- RUNTIME (stage) packages ---
    stage-packages:
      # Core image/codecs Geeqie actually uses
      - libexif12
      - libexiv2-27
      - libgexiv2-2
      - libjpeg-turbo8
      - libpng16-16
      - libtiff6
      - libwebp7
      - libheif1
      - libraw23
      - liblcms2-2
      - libfftw3-double3
      - libpoppler-glib8
      - shared-mime-info

      # ImageMagick (tools + configs) for scripts
      - imagemagick-6.q16
      - imagemagick-6-common

      # LAPACK/BLAS only because command chain sets LD_LIBRARY_PATH
      - libblas3
      - liblapack3

      # ---- OPTIONAL “extras” used by helpers ----
      - bc
      - exiftool
      - exiftran
      - gphoto2
      - zenity
      - yad

    override-prime: |
      set -eux
      craftctl default

      # stamp version even if adopt-info is set
      ver="$(git describe --tags --dirty --always 2>/dev/null || date +'%Y%m%d').edge"
      craftctl set version="$ver"

      # Debian alternatives don't run in snaps: create IM6 compat symlinks
      for tool in convert mogrify identify composite compare; do
        if [ -x "$CRAFT_PRIME/usr/bin/${tool}-im6.q16" ] && [ ! -e "$CRAFT_PRIME/usr/bin/$tool" ]; then
          ln -s "${tool}-im6.q16" "$CRAFT_PRIME/usr/bin/$tool"
        fi
      done

      # Make delegates.xml use in-snap libs (robust across distros)
      f="$CRAFT_PRIME/etc/ImageMagick-6/delegates.xml"
      [ -f "$f" ] && sed -i 's|/usr/lib/|${SNAP}/usr/lib/|g' "$f"

  launcher:
    plugin: nil
    source: .
    override-build: |
      install -Dm755 snap/local/env-imagemagick.sh "$CRAFT_PART_INSTALL/bin/env-imagemagick.sh"
      install -Dm755 snap/local/env-lapack.sh      "$CRAFT_PART_INSTALL/bin/env-lapack.sh"
    stage:
      - bin/env-imagemagick.sh
      - bin/env-lapack.sh
    build-environment:
      - LDFLAGS: -Wl,--as-needed -lzstd
      - MESON_PACKAGE_CACHE_DIR: $CRAFT_PART_BUILD/meson-packagecache
    build-packages:
      - appstream
      - build-essential
      - curl
      - gettext
      - libarchive-dev
      - libcfitsio-dev
      - libchamplain-0.12-dev
      - libdjvulibre-dev
      - libdw-dev
      - libffmpegthumbnailer-dev
      - libfftw3-dev
      - libgexiv2-dev
      - libglib2.0-dev
      - libgspell-1-dev
      - libgtk-3-dev
      - libheif-dev
      - libimath-dev
      - libjpeg-turbo8-dev
      - libjxl-dev
      - liblcms2-dev
      - liblua5.3-dev
      - libomp-dev
      - libopenexr-dev
      - libpango1.0-dev
      - libpng-dev
      - libpoppler-glib-dev
      - libraw-dev
      - librsvg2-dev
      - libtiff-dev
      - libunwind-dev
      - libwebp-dev
      - libzstd-dev
      - meson
      - ninja-build
      - pandoc
      - pkg-config
      - xsltproc
      - yelp-tools
